version: '3.1'

services:
    redis:
        image: redis:latest
        container_name: redis
        # command: redis-server --requirepass password_here # for redis password
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379
        networks:
            - service

networks:
  service:
    external: true
    name: net