version: '3.1'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        volumes:
            - /Users/mfathirirhas/.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - /Users/mfathirirhas/.docker/rabbitmq/logs/:/var/log/rabbitmq/
            - /Users/mfathirirhas/.docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        environment:
            - RABBITMQ_ERLANG_COOKIE=cluster_cookie
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            # - 15672:15672
        networks:
            - service

networks:
  service:
    external: true
    name: net