version: "3.1"

services: 
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=test
        volumes: 
            - mongodb-data:/var/lib/mongodb
        ports: 
            - 27017:27017
        expose: 
            - 27017

volumes: 
    mongodb-data: