# brew tap sergiobenitez/osxct
# brew install x86_64-unknown-linux-gnu
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

# brew tap filosottile/musl-cross
# brew install musl-cross
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

# brew install mingw-w64
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
