inherits = "catppuccin_mocha"

# blocked area by cursor
"ui.selection" = { bg = "abu_selection_color" }
# blocked area of current cursor in multiple selection
"ui.selection.primary" = { bg = "abu_selection_primary_color" }
"ui.virtual.inlay-hint" = { fg = "overlay0", bg = "base" }

[palette]
base = "#1d2129"
abu_selection_color = "#444651"
abu_selection_primary_color = "#545662"

