inherits = "catppuccin_mocha"

# blocked area by cursor
"ui.selection" = { bg = "abu_selection_color" }
# blocked area of current cursor in multiple selection
"ui.selection.primary" = { bg = "abu_selection_primary_color" }
"ui.virtual.inlay-hint" = { fg = "overlay0", bg = "base" }

"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "base", bg = "lavender" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "base", bg = "lavender" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "rosewater" }

"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.select" = { fg = "base", bg = "secondary_cursor_select" }

[palette]
base = "#1d2129"
abu_selection_color = "#444651"
abu_selection_primary_color = "#545662"

cursorline = "#2a2b3c"
secondary_cursor = "#878ec0"
secondary_cursor_select = "#b5a6a8"
secondary_cursor_normal = "#878ec0"
secondary_cursor_insert = "#7ea87f"

