# theme = "catppuccin_mocha"
theme = "abu"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
preview-completion-insert	= false

[editor.indent-guides]
render = true
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
# left = ["mode", "spinner", "separator", "version-control", "separator"]
# "workspace" is PR from https://github.com/helix-editor/helix/pull/11035
left = ["mode", "spinner", "separator", "version-control", "separator", "workspace"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["register", "diagnostics", "workspace-diagnostics", "file-type", "file-line-ending", "selections", "total-line-numbers", "position", "file-encoding"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"y" = ":clipboard-yank"
"Y" = "yank"
"A-y" = ":clipboard-yank-join"
"p" = ["paste_before"]
"P" = ["paste_after"]
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
# cut
"D" = [":clipboard-yank", "delete_selection_noyank"]
# shift line/selections down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# shift line/selections up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"y" = ":clipboard-yank"
"Y" = "yank"
"A-y" = ":clipboard-yank-join"
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
"A-z" = ["collapse_selection", "normal_mode"]
# cut
"D" = [":clipboard-yank", "delete_selection_noyank"]
# shift line/selections down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# shift line/selections up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
"C-space" = "completion"
"C-c" = "toggle_comments"
"A-z" = ["normal_mode", "collapse_selection"]
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"

# git mode 
[keys.normal.G]
g = ":sh git status -vb"
b = ":sh git branch -v"
r = ":sh git branch -vr"
t = ":sh git tag"
u = ":reset-diff-change"

# terminal mode
[keys.normal.T]
p = ":sh wezterm cli list"

# languages mode
## rust
[keys.normal.L.r]
c = ":sh cargo check 2>&1"
t = ":sh cargo test -- --exact --nocapture 2>&1"
b = ":sh cargo build 2>&1"

# file-tree explorer config
# merged from PR: https://github.com/helix-editor/helix/pull/5768
[editor.explorer]
column-width = 50
