# theme = "catppuccin_mocha"
theme = "abu"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
preview-completion-insert	= false
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control", "separator", "current-working-directory"]
## "workspace" is PR from https://github.com/helix-editor/helix/pull/11035
# left = ["mode", "spinner", "separator", "version-control", "separator", "workspace"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["register", "diagnostics", "workspace-diagnostics", "file-type", "file-line-ending", "selections", "total-line-numbers", "position", "file-encoding"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"y" = ":clipboard-yank"
"Y" = "yank"
"A-y" = ":clipboard-yank-join"
"p" = ["paste_before"]
"P" = ["paste_after"]
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
# cut
"D" = [":clipboard-yank", "delete_selection_noyank"]
# shift line/selections down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# shift line/selections up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# go to tabs on the right
"A-}" = ["goto_next_buffer"]
# go to tabs on the left
"A-{" = ["goto_previous_buffer"]
# close current tab/buffer
"A-w" = ":buffer-close"

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"y" = ":clipboard-yank"
"Y" = "yank"
"A-y" = ":clipboard-yank-join"
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
"A-z" = ["collapse_selection", "normal_mode"]
# cut
"D" = [":clipboard-yank", "delete_selection_noyank"]
# shift line/selections down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# shift line/selections up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# go to tabs on the right
"A-}" = ["goto_next_buffer"]
# go to tabs on the left
"A-{" = ["goto_previous_buffer"]
# close current tab/buffer
"A-w" = ":buffer-close"

[keys.insert]
"C-space" = "completion"
"C-c" = "toggle_comments"
"A-z" = ["normal_mode", "collapse_selection"]
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"

### Custom Mode
# Custom key bindings
# git mode 
[keys.normal.G]
g = ":sh git status -vb"
b = ":sh git blame -L %{selection_line_start},%{selection_line_end} %{buffer_name}"
r = ":sh git branch -v"
t = ":sh git tag"
u = ":reset-diff-change"

# terminal mode
## shortcuts for other things
[keys.normal.T]
p = ":sh wezterm cli list"
# copy current buffer relative path(relative to current workspace root)
y = ":sh echo \"%{buffer_name}\" | pbcopy"
# copy current buffer full path
Y = ":sh echo \"%{workspace_directory}/%{buffer_name}\" | pbcopy"

## languages mode
# rust
[keys.normal.L.r]
c = ":sh cargo check 2>&1"
a = ":sh echo \"cargo test -- --nocapture\" | pbcopy"
t = ":sh echo \"cargo test %{selection} -- --nocapture\" | pbcopy"
b = ":sh cargo build 2>&1"

# golang
[keys.normal.L.g]
# Run all tests
a = ":sh echo \"go test -v -cover -race\" ./... | pbcopy"
# Run test for a test function inside a directory/package
t = ":sh echo \"go test -v -cover -race -run %{selection}\" %sh{dirname %{workspace_directory}/%{buffer_name}} | pbcopy"
# Run all tests inside a directory/package
p = ":sh echo \"go test -v -cover -race\" %sh{dirname %{workspace_directory}/%{buffer_name}} | pbcopy"
# clean test cache
c = ":sh go clean -testcache"

# file-tree explorer config
# merged from PR: https://github.com/helix-editor/helix/pull/5768
# [editor.explorer]
# column-width = 50
# # source: https://github.com/mfirhas/helix/commit/64e69caf32d358ba8ce4b4d03be329b68c850190#diff-90493a3122e39c4af3ab5f7981bfb82ac755b79174a2fb13e801bec7d416adf0R41
# ignore-list = [
#   ".git/", 
#   ".DS_Store", 
#   "target/", 
#   ".idea/", 
#   ".pytest_cache/"
#   ]
