# theme = "catppuccin_mocha"
theme = "abu"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
preview-completion-insert	= false

[editor.indent-guides]
render = true
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control", "separator"]
center = ["file-base-name", "read-only-indicator", "file-modification-indicator"]
right = ["register", "diagnostics", "workspace-diagnostics", "total-line-numbers", "file-type", "file-line-ending", "selections", "position", "file-encoding"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"H" = ["goto_window_top"]
"M" = ["goto_window_center"]
"L" = ["goto_window_bottom"]
"p" = ["paste_before"]
"P" = ["paste_after"]
"y" = ":clipboard-yank"
"Y" = "yank"
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"H" = ["goto_window_top"]
"M" = ["goto_window_center"]
"L" = ["goto_window_bottom"]
"y" = ":clipboard-yank"
"Y" = "yank"
"R" = ":clipboard-paste-replace"
"A-r" = "replace_with_yanked"
"A-z" = ["normal_mode", "collapse_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
"C-space" = "completion"
"A-z" = ["normal_mode", "collapse_selection"]
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"

