# theme = "catppuccin_mocha"
theme = "abu"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "separator" , "version-control", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "workspace-diagnostics", "total-line-numbers", "file-type", "file-line-ending", "selections", "register", "position", "file-encoding"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"H" = ["goto_window_top"]
"M" = ["goto_window_center"]
"L" = ["goto_window_bottom"]
"p" = ["paste_before"]
"P" = ["paste_after"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"H" = ["goto_window_top"]
"M" = ["goto_window_center"]
"L" = ["goto_window_bottom"]

[keys.insert]
"C-space" = "completion"
