# theme = "catppuccin_mocha"
theme = "abu"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"H" = ["goto_window_top"]
"M" = ["goto_window_center"]
"L" = ["goto_window_bottom"]
