# RUST
[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
# '<' = '>'

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /usr/local/etc/lldb_vscode_rustc_primer.py" ] }

# GOLANG
[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]
auto-format = true

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--enable-all",
  "--verbose",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

# YAML
[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[language-server.yaml-language-server]
config = { yaml = { customTags = ["!anything"] } }
