[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /usr/local/etc/lldb_vscode_rustc_primer.py" ] }

# golang lint server
# enable all lints
[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--enable-all",
  "--verbose",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]
